Repository hot5667/udon_restaurant, pull requests merged in 2024-09, with the labels that each got.

#4 회원 가입 기능 및 로그인 기능 개편 및 성능 개선중Kim branch
  .gitignore
  package.json
  src/App.jsx
  src/Router.jsx
  src/components/AuthCallback.jsx
  src/main.jsx
  src/pages/AlreadyRegistered.jsx
  src/pages/Profile.jsx
  src/pages/UpdateProfile.jsx
  src/pages/UserProfile.jsx
  src/pages/signIn.jsx
  src/pages/signUp.jsx
  src/pages/tododevlist.txt
  src/supaBasecClient.js
  src/util/utils.js
  vite.config.js
  yarn.lock
Labels: 버그, 코드설명, 작업중

#2 update : 댓글 추가 기능
  package.json
  src/App.jsx
  src/components/Comment.jsx
  yarn.lock
Labels: 코드설명, 병합, 작업중

#1 게시글 추가/수정 기능 완성 및 메인페이지 최신글 띄우기 완성
  eslint.config.js
  package.json
  src/App.jsx
  src/components/CreateForm.jsx
  src/components/RecentPost.jsx
  src/components/RecentPosts.jsx
  src/components/Test.jsx
  src/context/PostContext.jsx
  src/main.jsx
  src/pages/CreatePostPage.jsx
  src/pages/MainPage.jsx
  src/reset.css
  src/shared/Router.jsx
  yarn.lock
Labels: 코드설명, 병합

#7 [update] 게시글 수정 기능 완료 및 메인 페이지 최신글 캐러셀 추가
  package.json
  src/components/EmblaCarouselArrowButtons.jsx
  src/components/RecentPost.jsx
  src/components/RecentPosts.jsx
  yarn.lock
Labels: 병합

#8 이미지 가져오기 미완성
  src/components/DeletePost.jsx
  src/pages/PostDetail.jsx
  src/pages/TestPages.jsx
Labels: 코드설명, 병합, 작업중

#10 Router 수정, page 폴더 만들어서 파일 정리
  .gitignore
  eslint.config.js
  package.json
  src/App.jsx
  src/Router.jsx
  src/components/AuthCallback.jsx
  src/components/Comment.jsx
  src/components/CreateForm.jsx
  src/components/RecentPost.jsx
  src/components/RecentPosts.jsx
  src/context/PostContext.jsx
  src/main.jsx
  src/pages/create-post-page/CreatePostPage.jsx
  src/pages/login-page/AlreadyRegistered.jsx
  src/pages/login-page/SocialSignUp.jsx
  src/pages/login-page/signIn.jsx
  src/pages/login-page/signUp.jsx
  src/pages/main-page/MainPage.jsx
  src/pages/my-page/Profile.jsx
  src/pages/my-page/UpdateProfile.jsx
  src/pages/post-page/PostDetail.jsx
  src/pages/tododevlist.txt
  src/reset.css
  src/supaBasecClient.js
  src/util/utils.js
  vite.config.js
  yarn.lock
Labels: 코드설명, 병합

#13 [tmp] 사이드바 임시 pr
  package.json
  src/App.jsx
  src/Router.jsx
  src/components/CreateForm.jsx
  src/components/PostCard.jsx
  src/components/PostList.jsx
  src/components/RecentPost.jsx
  src/context/PostContext.jsx
  src/pages/PostListPage.jsx
  src/pages/create-post-page/CreatePostPage.jsx
  src/pages/main-page/MainPage.jsx
Labels: 작업중

#16 로그인 기능 구현 및 소셜 로그인 구현
  src/Router.jsx
  src/components/AuthCallback.jsx
  src/components/CitySelect.jsx
  src/components/FromField.jsx
  src/context/PostContext.jsx
  src/pages/login-page/SocialSignUp.jsx
  src/pages/login-page/signIn.jsx
  src/pages/login-page/signUp.jsx
  src/pages/my-page/myPage.jsx
Labels: 코드설명, 병합

#15 update : 사이드바 계속 보이게 Outlet추가
  src/Router.jsx
  src/components/WrapperComponent.jsx
  src/components/sideBar.jsx
  src/pages/login-page/AlreadyRegistered.jsx
  src/pages/post-page/PostDetail.jsx
Labels: 코드설명, 작업중

#18 Kim branch
  src/Router.jsx
  src/components/PostCard.jsx
  src/components/sideBar.jsx
  src/context/AuthContext.jsx
  src/context/PostContext.jsx
  src/pages/login-page/signIn.jsx
  src/pages/login-page/signUp.jsx
  src/pages/main-page/MainPage.jsx
  src/pages/post-page/PostDetail.jsx
  src/pages/tododevlist.txt
Labels: 병합, 작업중

#20 Cho branch
  src/components/CreateForm.jsx
  src/components/PostCard.jsx
  src/components/PostList.jsx
  src/components/RecentPost.jsx
  src/components/RecentPosts.jsx
  src/components/sideBar.jsx
  src/img/add-post-icon.svg
  src/img/empty-icon.png
  src/img/heart-icon.svg
  src/pages/PostListPage.jsx
  src/pages/main-page/MainPage.jsx
  src/pages/post-page/PostDetail.jsx
Labels: 병합

#21 update : Detail 페이지에 댓글 리스트, 추가 기능 구현
  .prettierrc
  README.md
  index.html
  package.json
  src/App.jsx
  src/Router.jsx
  src/component/myPage.jsx
  src/component/mypage2.jsx
  src/component/sidde2.jsx
  src/components/AuthCallback.jsx
  src/components/CitySelect.jsx
  src/components/Comment.jsx
  src/components/CreateForm.jsx
  src/components/DeletePost.jsx
  src/components/EmblaCarouselArrowButtons.jsx
  src/components/FetchData.jsx
  src/components/FromField.jsx
  src/components/PostCard.jsx
  src/components/PostList.jsx
  src/components/RecentPost.jsx
  src/components/RecentPosts.jsx
  src/components/WrapperComponent.jsx
  src/components/sideBar.jsx
  src/context/PostContext.jsx
  src/css/font.css
  src/fonts/fonts.css
  src/img/default-img.png
  src/img/logo-gradation.png
  src/img/main-logo.png
  src/main.jsx
  src/pages/PostListPage.jsx
  src/pages/TestPages.jsx
  src/pages/create-post-page/CreatePostPage.jsx
  src/pages/login-page/AlreadyRegistered.jsx
  src/pages/login-page/SocialSignUp.jsx
  src/pages/login-page/signIn.jsx
  src/pages/login-page/signOut.jsx
  src/pages/login-page/signUp.jsx
  src/pages/main-page/MainPage.jsx
  src/pages/my-page/myPage.jsx
  src/pages/post-page/PostDetail.jsx
  src/pages/test.jsx
  src/pages/tododevlist.txt
  src/shared/Router.jsx
  src/supaBasecClient.js
  yarn.lock
Labels: 코드설명, 작업중

#22 상세페이지완성
  src/components/DeletePost.jsx
  src/components/PostCard.jsx
  src/context/PostContext.jsx
  src/img/image.png
  src/pages/post-page/PostDetail.jsx
Labels: 병합

#29 리플레쉬 에러
  src/pages/login-page/SocialSignUp.jsx
  src/pages/login-page/signUp.jsx
  src/pages/post-page/PostDetail.jsx
Labels: 버그
